name: ${project.name}
main: com.poixson.itemeconomy.ItemEconomyPlugin
version: '${project.version}'
api-version: '${bukkit-short-version}'
depend:
  - pxnPluginLib
  - Vault
authors: [ lorenzop ]
website: ${project.url}
description: ${project.description}
permissions:
    itemeconomy.*:
        default: op
        description: Gives access to all Item Economy commands.
        children:
            itemeconomy.cmd.balance:        true
            itemeconomy.cmd.balance.top:    true
            itemeconomy.cmd.balance.others: true
    itemeconomy.cmd.balance:
        default: true
        description: Allow the /balance command.
    itemeconomy.cmd.balance.top:
        default: true
        description: Allow the /balance top command.
    itemeconomy.cmd.balance.others:
        default: op
        description: Allow the /balance <player> command.
